package trabalhoUninter;

// CLASSE ABSTRATA PARA SERVIR DE MOLDE PARA OUTRAS CLASSES (UMA CLASSE "MÃE")
public abstract class Moeda {
	
	double valor; // ATRIBUTO PARA ARMAZENAR O VALOR DA MOEDA
	
	public abstract void info(); // MÉTODO ABSTRATO PARA EXIBIR INFORMAÇÕES DA MOEDA QUE SERÁ IMPLEMENTADO NAS CLASSES FILHAS
	public abstract double converter(); // MÉTODO PARA CONVERTER O VALOR DA MOEDA QUE SERÁ IMPLEMENTADO NAS CLASSES FILHAS
	
}
